language: node_js
node_js: stable
 
# S: Build Lifecycle
install:
  - npm install hexo-cli -g
  - npm install hexo --save
  - npm install
 
#before_script:
 # - npm install -g gulp
 
script:
  - hexo g
 
after_script:
  - cd ./public
  - git init
  - git config user.name "freereaper"
  - git config user.email "freereaper@aliyun.com"
  - git add .
  - git commit -m "Travis CI Auto Builder"
  - git push --force --quiet "https://${GitHubKEY}@${GitHubREF}" master:master
# E: Build LifeCycle
 
branches:
  only:
    - blog-source
env:
 global:
   - GitHubREF: github.com/freereaper/freereaper.github.io.git</code>
